---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - ruby-bundler

install:
  # Install ansible
  - pip install ansible==2.4.0.0
  - pip install ansible-lint

  # Check ansible version
  - ansible --version
  - ansible-lint --version
  - rubocop --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - rubocop -ES
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint -pv test.yml
  - kitchen test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
