---
language: python

sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - ruby-bundler

install:
  - bundle install
  - pip install --cache-dir $HOME/.cache/pip -r requirements.txt

  # Check versions
  - ansible --version
  - ansible-lint --version
  - rubocop --version

script:
  - $CHECK

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: CHECK="rubocop -ES"
  - python: 2.7
    env: CHECK="ansible-playbook test.yml -i inventories/kitchen --syntax-check"
  - python: 2.7
    env: CHECK="ansible-lint -pv test.yml"
  - python: 2.7
    env: CHECK="kitchen test test-kitchen-ubuntu-1404"
